Job.delete_all
Job.create(title: 'User Experience Designer', company: 'WebstaurantStore', url: 'http://www.webstaurantstore.com/careers.html', location: 'Lancaster, PA')
Job.create(title: 'Lead Designer', company: 'Wow!works', url: 'http://www.wowworks.eu/nl/designer/', location: 'Amsterdam, the Netherlands')
Job.create(title: 'Product Designer', company: 'Palantir', url: 'https://www.palantir.com/careers/OpenPosDetail?id=a0m80000000iQpM', location: 'Palo Alto, CA')
Job.create(title: 'Visual Designer', company: 'Palantir', url: 'https://www.palantir.com/careers/OpenPosDetail?id=a0m80000005cjnIAAQ', location: 'Palo Alto, CA')
Job.create(title: 'Designer', company: 'Code School', url: 'https://www.codeschool.com/jobs', location: 'Orlando, FL')
Job.create(title: 'Product Designer', company: 'Crowdtap', url: 'http://boards.greenhouse.io/crowdtap/jobs/14901', location: 'New York, NY')
Job.create(title: 'Senior Designer', company: 'Attik', url: 'http://www.attik.com/job/senior-designer/', location: 'San Francisco, CA')
Job.create(title: 'Senior Interaction Designer', company: 'BCG Digital Ventures', url: 'https://www.bcgdv.com/jobs/BCGDV_Sr_Interaction_Designer.html', location: 'Manhattan Beach, CA')
Job.create(title: 'Senior Presentation Designer', company: 'BCG Digital Ventures', url: 'https://www.bcgdv.com/jobs/BCGDV_Sr_Presentation_Designer.html', location: 'Manhattan Beach, CA')
Job.create(title: 'UX Designer', company: 'Fire Eye', url: 'http://newton.newtonsoftware.com/career/JobIntroduction.action?clientId=8aa00506326e915601326f65b82e1fcb&id=8a87142e489b99750148b3b723916bce&source=', location: 'New York, NY')
Job.create(title: 'Product Designer', company: 'Mention', url: 'http://mention.workable.com/jobs/21542', location: 'Paris')
Job.create(title: 'Principal UX Designer', company: 'Mercedes-Benz RD NA, Inc.', url: 'https://recruitment.daimler.com/psc/hr90pwext/EMPLOYEE/HRMS/c/HRS_HRAM.HRS_CE.GBL?Page=HRS_CE_HM_PRE&Action=A&TargetFrameName=None', location: 'Sunnyvale, CA')
Job.create(title: 'Senior Designer', company: 'thirteen23', url: 'http://thirteen23.com/contact/#senior-designer', location: 'Austin')
$Job.create(title: 'UI/UX Designer', company: 'Walker and company Brands', url: '', location: 'Palo Alto, CA')
Job.create(title: 'Product Designer (Visual & UX)', company: 'Pivotal Labs', url: '', location: 'Toronto, Canada')
Job.create(title: 'Senior Web / Graphic Designer', company: 'RateHub', url: '', location: 'Downtown Toronto')
Job.create(title: 'Associate Designer, Freelance', company: 'Demand Media', url: '', location: 'Santa Monica')
Job.create(title: 'Designer', company: 'Scout Monitoring', url: '', location: 'Anywhere (US)')
Job.create(title: 'Senior Front End Developer', company: 'ThinkCERCA', url: '', location: 'Chicago or Remote')
Job.create(title: 'UI/UX Designer', company: 'FreeAssociation', url: '', location: 'Brooklyn, NY')
Job.create(title: '', company: 'Narrative', url: '', location: '')
Job.create(title: '', company: 'Good Eggs', url: '', location: '')
Job.create(title: '', company: 'The Rockstar Development Company', url: '', location: '')
Job.create(title: '', company: 'Formstack.com', url: '', location: '')
Job.create(title: 'Graphic Designer', company: 'Pine Cove Camps', url: 'http://pinecove.force.com/careers/ts2__JobDetails?jobId=a0WU00000054DGyMAM&tSource=', location: 'Tyler, TX')
Job.create(title: 'Senior UX Designer', company: 'Booking.com', url: '', location: 'Amsterdam, the Netherlands')
Job.create(title: 'Full Time Senior WordPress Developer', company: 'SPARK Experience', url: '', location: 'Bethesda, MD')
Job.create(title: 'Digital Designer', company: 'MyBuilder', url: '', location: 'Clerkenwell, London')
Job.create(title: 'UX/UI Designer', company: 'Shizzle', url: '', location: 'London, UK')
Job.create(title: 'Creative Director', company: 'Brooklyn United', url: '', location: 'New York, NY')
Job.create(title: 'Senior Design Lead', company: 'Coolfire Solutions', url: '', location: 'St. Louis, MO')
Job.create(title: 'Web Designer', company: 'Gregor LLC', url: '', location: 'Belgrade, Serbia')
Job.create(title: 'Visual Designer', company: 'Greenlind', url: '', location: 'San Francisco, CA')
Job.create(title: 'Graphic Designer', company: 'Verve Coffee Roasters', url: '', location: 'Santa Cruz, CA')
Job.create(title: 'Product Designer', company: 'Livefyre', url: '', location: 'San Francisco, CA')
Job.create(title: 'UX Designer', company: 'Sharethrough', url: '', location: 'San Francisco, CA')
Job.create(title: 'Product Designer (Visual Interface)', company: 'Architizer', url: '', location: 'New York, NY')
Job.create(title: 'Creative Lead', company: 'Truth Labs', url: '', location: 'Chicago')
Job.create(title: 'Design Coordinator', company: 'Opera Mediaworks', url: '', location: 'New York, NY')
Job.create(title: 'Senior UX Designer', company: 'Weebly', url: '', location: 'San Francisco, CA')
Job.create(title: 'Web & UI Designer/Developer', company: 'Opera Mediaworks', url: '', location: 'San Mateo, CA')
Job.create(title: 'Front-End Developer', company: 'Booking.com', url: '', location: 'Amsterdam, the Netherlands')
Job.create(title: 'Product Designer', company: 'Academia.edu', url: '', location: 'San Francisco, CA')
Job.create(title: 'Interface Designer', company: 'Capsure', url: '', location: 'Manchester, UK')
Job.create(title: 'Designer (UI/UX)', company: 'VTS', url: '', location: 'New York, NY')
Job.create(title: 'Junior Designer', company: 'Bloc', url: '', location: 'San Francisco, CA')
Job.create(title: 'Senior UI Designer/Front-End Developer', company: 'Creative Circle', url: '', location: 'San Francisco, CA')
Job.create(title: 'UX Designer', company: 'Expedite', url: '', location: 'San Francisco, CA')
Job.create(title: 'UX Designer', company: 'Digital Telepathy', url: '', location: 'San Diego, CA')
Job.create(title: 'UI/UX Intern', company: 'Momentum Design Lab', url: '', location: 'San Mateo, CA')
Job.create(title: 'Mid to Senior UI/UX Designers', company: 'Momentum Design Lab', url: '', location: 'San Mateo, CA')
Job.create(title: 'Product/UI/UX/Visual Designers', company: "Designer Fund's Bridge", url: '', location: 'San Francisco Bay Area, CA')
Job.create(title: 'Front End Web Developer', company: 'Red Ventures', url: '', location: 'Charlotte, NC')
Job.create(title: 'Junior Designer', company: 'Badoo', url: '', location: 'SOHO, London, UK')
Job.create(title: 'Designer/Team', company: 'LetsHost', url: '', location: 'Anywhere')
Job.create(title: 'Experience Design Manager', company: 'OpenTable', url: '', location: 'Chattanooga, TN')
Job.create(title: 'Product Designer', company: 'Pixel Union', url: '', location: 'Anywhere')
Job.create(title: 'Lead Product and UI Designer', company: 'Talkray', url: '', location: 'Redwood City')
Job.create(title: 'Vector Illustrator', company: 'Illustrio', url: '', location: 'Anywhere')
Job.create(title: 'Product Designer', company: 'underdog.io', url: '', location: 'New York, NY')
Job.create(title: 'Visual Designer', company: 'Clarity Consulting', url: '', location: 'Chicago, IL')
Job.create(title: 'Senior Visual Designer', company: 'Noom', url: '', location: 'NYC, NY')
Job.create(title: 'UX Designer', company: 'Pro.com', url: '', location: 'Seattle, WA')
Job.create(title: 'Front End Developer', company: 'Gazelle', url: '', location: 'Boston')
Job.create(title: 'Lead Product Designer', company: 'Evernote Design', url: '', location: 'Redwood City, CA')
Job.create(title: 'Product Designer | Windows', company: 'Evernote Design', url: '', location: 'Redwood City, CA')
Job.create(title: 'Senior Front End Developer', company: 'RxREVU', url: '', location: 'Denver')
Job.create(title: 'Visual/UI Designer(Mobile Application)', company: 'TLTalk', url: '', location: 'Seoul, South Korea')
Job.create(title: 'Front End Designer', company: 'Helix Education', url: '', location: 'Denver, SLC, San Francisco, Chicago')
Job.create(title: 'UI/UX Designer', company: 'EatStreet', url: '', location: 'Madison, WI')
Job.create(title: 'Designer', company: 'Smashing Boxes', url: '', location: 'Durham, NC')
Job.create(title: 'Visual Designer', company: 'Enertiv', url: '', location: 'New York, NY')
Job.create(title: 'Designer', company: 'Segment', url: '', location: 'San Francisco, CA')
Job.create(title: 'Asst. Mgr. Creative Design', company: 'Texas A&M Athletics Dept.', url: '', location: 'College Station, TX')
Job.create(title: 'UI/UX Designer', company: 'Zoomer', url: '', location: 'Anywhere')
Job.create(title: 'Designer/Front-End Developer', company: 'Beggars Group', url: '', location: 'New York, NY')
Job.create(title: 'Mobile UX/UI Designer', company: 'Prolific Interactive', url: '', location: 'Brooklyn, San Francisco')
$Job.create(title: 'Senior Visual Designer', company: 'HealthTap', url: '', location: 'Palo Alto, CA')
Job.create(title: 'Interactive UX Designer', company: 'NuOrbit Media', url: 'http://www.nuorbit.com/careers/', location: 'Indianapolis')
Job.create(title: 'Web Designer', company: 'Precise Leads', url: 'http://www.preciseleads.com/about-us-jobs.asp#jobs_2_a', location: 'New York, NY')
Job.create(title: 'Sr. Product Designer - Native Apps', company: 'Wikia', url: 'http://www.jobscore.com/jobs2/wikiainc/sr-product-designer-native-apps/dK623gwJGr5jg5iGalkWKP?detail=Dribbble&remail=&rfirst=&rlast=&sid=161', location: 'San Francisco, CA')
Job.create(title: 'UI/UX Designer', company: 'Career Cruising', url: 'https://www.linkedin.com/jobs2/view/25731921?trk=biz-overview-job-post', location: 'Toronto, Canada')
Job.create(title: 'User Experience Designer', company: 'WyzAnt', url: 'http://wyzanttutoring.theresumator.com/apply/k5rzzL/User_Experience_Designer.html', location: 'Chicago, IL')
Job.create(title: 'Product Designer', company: 'Circle', url: 'http://circle.theresumator.com/apply/9RqJBx/Product-Designer.html', location: 'Boston, MA')
Job.create(title: 'Front End Web Developer', company: 'Plow & Heath, LLC', url: 'https://plowandhearth.applicantpro.com/jobs/139556.html', location: 'Madison, VA')
Job.create(title: 'Product Designer', company: 'Trunk Club', url: 'http://trunkclub.theresumator.com/apply/6QfqGW/Product-Designer.html', location: 'Chicago, IL or New York, NY')
Job.create(title: 'Product Designer', company: 'GitHub', url: 'https://jobs.github.com/positions/cec0b09e-5590-11e4-9b36-8b1b5efc4d04', location: 'Remote')
Job.create(title: 'Senior UX Designer', company: 'Fantasy Interactive', url: 'http://www.f-i.com/fi/careers/sr-ux-designer-san-francisco/oWWfWfwN', location: 'San Francisco, CA')
Job.create(title: 'Lead Interaction Designer', company: 'Idean', url: 'http://www.idean.com/job/?job_id=oDdNZfwm', location: 'Austin, TX')
Job.create(title: 'Front-End Developer/Designer', company: 'shyftplan.com', url: 'https://www.dropbox.com/s/ryts23k2njowmn0/Ausschreibung_Front-End%20Developer.pdf?dl=0', location: 'Berlin')
Job.create(title: 'UI/UX Designer', company: 'Spiceworks', url: 'https://careers-spiceworks.icims.com/jobs/1204/ui---ux-designer/job', location: 'Austin, TX')
Job.create(title: 'Sr. Interaction Designers', company: 'Idean', url: 'http://www.idean.com/job/?job_id=obiNZfwZ', location: 'San Francisco, CA')
Job.create(title: 'Sr. Visual Designers', company: 'Idean', url: 'http://www.idean.com/job/?job_id=ociNZfw0', location: 'San Francisco, CA')
Job.create(title: 'Product Designer', company: 'Inkling', url: 'https://boards.greenhouse.io/inkling/jobs/25292', location: 'San Francisco, CA')
Job.create(title: 'Senior UI/UX Designer - Mobile', company: 'Schoology', url: 'http://www.jobscore.com/jobs2/schoology/senior-ui-ux-designer-mobile/bAFODCi7Wr5k8jiGalkWKP', location: 'New York, NY')
Job.create(title: 'Mobile Designer, Android', company: 'Udemy', url: 'http://www.jobscore.com/jobs2/udemy/mobile-designer-android/brqiYKvjqr5iztiGaltGfR', location: 'San Francisco, CA')
Job.create(title: 'UI/UX + Visual Designer (Web App)', company: 'Piktochart', url: 'http://piktochart.com/ui-ux-designer-web-vacancy/', location: 'Penang, Malaysia')
Job.create(title: 'Web Designer', company: 'Booking.com', url: 'https://workingatbooking.com/vacancies/web-designer/', location: 'Amsterdam, the Netherlands')
Job.create(title: 'Visual Designer', company: 'NationBuilder', url: 'http://nationbuilder.com/visual_designer', location: 'Los Angeles, CA')
Job.create(title: 'Graphic Designer (Contract)', company: 'Lookout Mobile Security', url: 'https://www.lookout.com/about/careers/detail?gh_jid=33743', location: 'San Francisco, CA')
Job.create(title: 'UX Designer', company: 'StackCommerce', url: 'http://hire.jobvite.com/CompanyJobs/Careers.aspx?nl=1&k=Job&j=oQ8qZfw7', location: 'Venice, CA')
Job.create(title: 'Front End Developer, Advertising', company: 'Pandora', url: 'http://www.pandora.com/careers/position?id=o5ANZfwb', location: 'Oakland, CA')
Job.create(title: 'Sr. Visual Designer', company: 'Pandora', url: 'http://www.pandora.com/careers/position?id=oT4KZfwq', location: 'Oakland, CA')
